config/routes.rb
Rails.application.routes.draw do
  resources :services, shallow: true do 
    resources :passengers
    resources :shuttles
  end 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "services#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :service
end

app/models/service.rb
class Service < ApplicationRecord
	has_many :shuttles
	has_many :passengers
	validates :description, :service_date, :presence => true
end

app/models/shuttle.rb
class Shuttle < ApplicationRecord
  belongs_to :service
  validates :description, :setoff_time, :max_capacity, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
  before_action :set_passenger, only: %i[ show edit update destroy ]
  before_action :get_service, except: %i[ show edit destroy]

  # GET /passengers or /passengers.json
  def index
    @passengers = Passenger.all
  end

  # GET /passengers/1 or /passengers/1.json
  def show
  end

  # GET /passengers/new
  def new
    @passenger = @service.passengers.build
  end

  # GET /passengers/1/edit
  def edit
  end

  # POST /passengers or /passengers.json
  def create
    @passenger = @service.passengers.build(passenger_params)

    respond_to do |format|
      if @passenger.save
        format.html { redirect_to passenger_url(@passenger), notice: "Passenger was successfully created." }
        format.json { render :show, status: :created, location: @passenger }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passengers/1 or /passengers/1.json
  def update
    respond_to do |format|
      if @passenger.update(passenger_params)
        format.html { redirect_to passenger_url(@passenger), notice: "Passenger was successfully updated." }
        format.json { render :show, status: :ok, location: @passenger }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passengers/1 or /passengers/1.json
  def destroy
    @passenger.destroy

    respond_to do |format|
      format.html { redirect_to passengers_url, notice: "Passenger was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def get_service
      @service = Service.find(params[:service_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_passenger
      @passenger = Passenger.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def passenger_params
      params.require(:passenger).permit(:service_id, :first_name, :last_name, :contact_number, :email, :number_of_seat, :service_id)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: %i[ show edit update destroy ]

  # GET /services or /services.json
  def index
    @services = Service.all.order('service_date asc')
  end

  # GET /services/1 or /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services or /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to service_url(@service), notice: "Service was successfully created." }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1 or /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to service_url(@service), notice: "Service was successfully updated." }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1 or /services/1.json
  def destroy
    @service.destroy

    respond_to do |format|
      format.html { redirect_to services_url, notice: "Service was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def service_params
      params.require(:service).permit(:description, :service_date)
    end
end

app/controllers/shuttles_controller.rb
class ShuttlesController < ApplicationController
  before_action :get_service, except: %i[ show edit destroy]
  before_action :set_shuttle, only: %i[ update ]

  # GET /shuttles or /shuttles.json
  def index
    @shuttles = @service.shuttles
  end

  # GET /shuttles/1 or /shuttles/1.json
  def show
    @shuttle = Shuttle.find(params[:id])
    @service = @shuttle.service
  end

  # GET /shuttles/new
  def new
    @shuttle = @service.shuttles.build
  end

  # GET /shuttles/1/edit
  def edit
    @shuttle = Shuttle.find(params[:id])
    @service = @shuttle.service
  end

  # POST /shuttles or /shuttles.json
  def create
    @shuttle = @service.shuttles.build(shuttle_params)

    respond_to do |format|
      if @shuttle.save
        format.html { redirect_to service_shuttles_url(params[:service_id]), notice: "Shuttle was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shuttles/1 or /shuttles/1.json
  def update
    respond_to do |format|
      if @shuttle.update(shuttle_params)
        format.html { redirect_to shuttle_url(@shuttle), notice: "Shuttle was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shuttles/1 or /shuttles/1.json
  def destroy
    @shuttle = Shuttle.find(params[:id])
    service_id = @shuttle.service_id
    @shuttle.destroy

    respond_to do |format|
      format.html { redirect_to service_shuttles_url(service_id), notice: "Shuttle was successfully destroyed." }
    end
  end

  private

    def get_service
      @service = Service.find(params[:service_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_shuttle
      @shuttle = @service.shuttles.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shuttle_params
      params.require(:shuttle).permit(:description, :setoff_time, :max_capacity, :service_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/shuttles_helper.rb
module ShuttlesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShuttleBooking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/passengers/_form.html.erb
<%= form_with(url: [service, passenger], scope: :passenger, class: "contents") do |form| %>
  <% if passenger.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(passenger.errors.count, "error") %> prohibited this passenger from being saved:</h2>

      <ul>
        <% passenger.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :contact_number %>
    <%= form.text_field :contact_number, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :email %>
    <%= form.text_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= collection_radio_buttons(:passenger, :id, service.shuttles, :id, :setoff_time) %>
  </div>

  <div class="my-5">
    <%= form.label :number_of_seat %>
    <%= form.number_field :number_of_seat, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/passengers/_passenger.html.erb
<tr class="bg-white border-b bg-gray-900 border-gray-700">
  <td class="text-center"><%= passenger.first_name %></td>
  <td class="text-center"><%= passenger.last_name %></td>
  <td class="text-center"><%= passenger.contact_number %></td>
  <td class="text-center"> <%= passenger.email %></td>
  <td class="text-center"> <%= passenger.number_of_seat %></td>
  <td class="text-center">  
    <% if action_name != "show" %>
      <%= link_to "Details", passenger, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %> 
      <%= link_to 'Edit', edit_passenger_path(passenger), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <% end %>
  </td>
</tr>

app/views/passengers/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing passenger</h1>

  <%= render "form", passenger: @passenger %>

  <%= link_to "Show this passenger", @passenger, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to passengers", passengers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/passengers/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Passengers</h1>
    <%= link_to 'New passenger', new_service_passenger_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <table class="table-auto w-full text-sm text-left text-gray-500 text-gray-400 text-centre">
    <thead class="text-xs text-gray-700 text-gray-400" >
      <tr>
        <th class="text-center">First Name</th>
        <th class="text-center">Last Name</th>
        <th class="text-center">Contact Number</th>
        <th class="text-center">Email</th>
        <th class="text-center">Number of Passengers</th>
        <th class="text-center">Actions</th>
      </tr>
    </thead>
    <tbody>
      <%= render @passengers %>
    </tbody>
  </table>

app/views/passengers/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New passenger</h1>

  <%= render "form", passenger: @passenger, service: @service%>

  <%= link_to 'Back to passengers', service_passengers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/passengers/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

      <div id="<%= dom_id @passenger %>">

        <p class="my-5">
          <strong class="block font-medium mb-1">First name:</strong>
          <%= @passenger.first_name %>
        </p>

        <p class="my-5">
          <strong class="block font-medium mb-1">Last name:</strong>
          <%= @passenger.last_name %>
        </p>

        <p class="my-5">
          <strong class="block font-medium mb-1">Contact number:</strong>
          <%= @passenger.contact_number %>
        </p>

        <p class="my-5">
          <strong class="block font-medium mb-1">Email:</strong>
          <%= @passenger.email %>
        </p>

        <p class="my-5">
          <strong class="block font-medium mb-1">Number of seat:</strong>
          <%= @passenger.number_of_seat %>
        </p>
      </div>

    <%= link_to 'Edit this passenger', edit_passenger_path(@passenger), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this passenger', passenger_path(@passenger), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to passengers', service_passengers_path(@passenger.service), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/services/_form.html.erb
<%= form_with(model: service, class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4") do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
        <% service.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-4">
    <%= form.label :description, class: "text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :description, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= form.label :service_date, class: "text-gray-700 text-sm font-bold mb-2" %>
    <%= form.date_field :service_date, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="flex items-center justify-between">
    <%= form.submit class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
<% end %>

app/views/services/_service.html.erb
<div id="<%= dom_id service %>">
  <p class="my-5">
    <strong class="font-medium mb-1">Description:</strong>
    <%= service.description %>
  </p>

  <p class="my-5">
    <strong class="font-medium mb-1">Service date:</strong>
    <%= service.service_date.strftime('%d/%m/%Y') %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "View", service, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit', edit_service_path(service), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Shuttles Available', service_shuttles_path(service), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Register Passenger', new_service_passenger_path(service), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/services/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing service</h1>

  <%= render "form", service: @service %>

  <%= link_to "View", @service, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to services", services_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/services/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Services</h1>
    <%= link_to 'New service', new_service_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="services" class="min-w-full">
    <%= render @services %>
  </div>
</div>

app/views/services/new.html.erb
<div class="w-full max-w-xs">
  <h1 class="font-bold text-4xl">New service</h1>

  <%= render "form", service: @service %>

  <%= link_to 'Back to services', services_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/services/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @service %>

    <%= link_to 'Edit', edit_service_path(@service), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Delete', service_path(@service), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to services', services_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/shuttles/_form.html.erb
<%= form_with(model: shuttle, class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4") do |form| %>
  <% if shuttle.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(shuttle.errors.count, "error") %> prohibited this shuttle from being saved:</h2>

      <ul>
        <% shuttle.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= hidden_field_tag 'service_id', shuttle.service_id %>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_field :description, class: "shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2" %>
  </div>

  <div class="my-5">
    <%= form.label :setoff_time %>
    <%= form.time_field :setoff_time, class: "shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2" %>
  </div>

  <div class="my-5">
    <%= form.label :max_capacity %>
    <%= form.number_field :max_capacity, class: "shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/shuttles/_shuttle.html.erb
<div id="<%= dom_id shuttle %>">
  <p class="my-5">
    <strong class="font-medium mb-1">Description:</strong>
    <%= shuttle.description %>
  </p>

  <p class="my-5">
    <strong class="font-medium mb-1">Setoff time:</strong>
    <%= shuttle.setoff_time %>
  </p>

  <p class="my-5">
    <strong class="font-medium mb-1">Max capacity:</strong>
    <%= shuttle.max_capacity %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this shuttle", shuttle, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this shuttle', edit_shuttle_path(shuttle), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/shuttles/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing shuttle</h1>

  <%= render "form", shuttle: @shuttle %>

  <%= link_to "Back to shuttles", service_shuttles_path(@shuttle.service_id), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/shuttles/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Shuttles</h1>
    <%= link_to 'New shuttle', new_service_shuttle_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="shuttles" class="min-w-full">
    <%= render @shuttles %>
  </div>
</div>

app/views/shuttles/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New shuttle</h1>

  <%= form_with(url: [@service, @shuttle], scope: :shuttle, class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4") do |form| %>
    <% if @shuttle.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(@shuttle.errors.count, "error") %> prohibited this shuttle from being saved:</h2>

        <ul>
          <% @shuttle.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="my-5">
      <%= form.label :description %>
      <%= form.text_field :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <%= form.label :setoff_time %>
      <%= form.time_field :setoff_time, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <%= form.label :max_capacity %>
      <%= form.number_field :max_capacity, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="inline">
      <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
    </div>
  <% end %>

  <%= link_to 'Back to shuttles', service_shuttles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/shuttles/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @shuttle %>

    <%= link_to 'Edit this shuttle', edit_shuttle_path(@shuttle), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this shuttle', shuttle_path(@shuttle), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to shuttles', service_shuttles_path(@shuttle.service_id), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>